services:
  auth_service:
    build: ./auth-service
    container_name: auth-service
    ports:
      - "8001:8000"
    depends_on:
      - mongo
      - redis
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - REDIS_HOST=redis 
  
  model_service:
    build: ./model-service
    container_name: model-service
    ports:
      - "8002:8000"
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  log_service:
    build: ./log-service
    container_name: log-service
    ports:
      - "8003:8000"
    depends_on:
      - memcached
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - MEMCACHED_HOST=memcached

  api-gateway:
    build: ./api-gateway
    container_name: api-gateway
    ports:
      - "8000:8000"
    depends_on:
      - auth_service
      - model_service
      - log_service
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
    - AUTH_SERVICE_URL=http://auth-service:8000
    - MODEL_SERVICE_URL=http://model-service:8000
    - LOG_SERVICE_URL=http://log-service:8000

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"

  memcached:
    image: memcached
    container_name: memcached-logs
    ports:
      - "11211:11211"

  redis:
      image: redis:latest
      container_name: redis-cache
      ports:
        - "6379:6379"
      restart: always
