services:
  app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    depends_on:
      - mongo
      - memcached
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - MONGO_URI=mongodb://mongo:27017/
      - MEMCACHED_HOST=memcached

  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"

  memcached:
    image: memcached
    container_name: memcached-logs
    ports:
      - "11211:11211"
